security:
  oauth2:
    client:
      clientId: account-service
      client-secret: my-account-service-password
      accessTokenUri: http://swisshackathonspringcloud-gateway.azuremicroservices.io/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      database: ${MONGODB_DATABASE}
      uri: ${MONGODB_URI}
  zipkin:
    sender:
      type: web

server:
  servlet:
    context-path: /accounts

feign:
  hystrix:
    enabled: true

